---
- name: install PKI
  hosts: localhost
  become: true
  vars:
    crypto_dir: /etc/certs
  remote_user: "root"
  tasks:

   - name: install python applications
     pip:
       name: pyopenssl

   - name: make dir
     file:
       path: "{{ crypto_dir }}"
       state: directory

##Cryptographic files

   - name: create CA keypair
     openssl_privatekey:
       path: "{{ crypto_dir }}/site.key"
       size: 2048

   - name: create CA csr
     openssl_csr:
       path: "{{ crypto_dir }}/site.csr"
       privatekey_path: "{{ crypto_dir }}/site.key"
       common_name: "{{ ansible_hostname }}"
       basic_constraints: "CA:TRUE"

   - name: create CA cert
     openssl_certificate:
       path: "{{ crypto_dir }}/site.crt"
       privatekey_path: "{{ crypto_dir }}/site.key"
       csr_path: "{{ crypto_dir }}/site.csr"
       provider: selfsigned

   - name: create server key
     openssl_privatekey:
       path: "{{ crypto_dir }}/server.key"
       size: 2048

   - name: create server csr
     openssl_csr:
       path: "{{ crypto_dir }}/server.csr"
       privatekey_path: "{{ crypto_dir }}/server.key"
       common_name: server.site.com
       key_usage:
         - digitalSignature
         - keyAgreement
       extended_key_usage:
         - clientAuth

   - name: create server cert from ca
     openssl_certificate:
       path: "{{ crypto_dir }}/server.site.crt"
       csr_path: "{{ crypto_dir }}/server.csr"
       ownca_path: "{{ crypto_dir }}/site.crt"
       ownca_privatekey_path: "{{ crypto_dir }}/site.key"
       provider: ownca

##Create configs
   - name: Copy apache2.conf to site root
     copy:
       src: apache2.conf
       dest: "/etc/apache2/sites-available/{{ server_ip }}.conf"

   - name: Update conf with IP address
     lineinfile:
       path: "/etc/apache2/sites-available/{{ server_ip }}.conf"
       regexp: '^(.*)   Redirect permanent / https://instance_IP(.*)$'
       line: '   Redirect permanent / https://{{ server_ip }}'

   - name: Update redirect with IP address
     replace:
       path: "/etc/apache2/sites-available/{{ server_ip }}.conf"
       regexp: '^(.*)   ServerName instance_IP(.*)$'
       replace: '   ServerName {{ server_ip }}'

# Enable HTTPs
   - name: Turn on HTTPs
     command: "sudo a2ensite {{ server_ip }}.conf"

## Start apache
   - name: Make sure Apache is running
     systemd:
       name: apache2@server
       state: restarted
       enabled: yes
     
